demontpx_user_security_login:
    path:     /login
    defaults: { _controller: DemontpxUserBundle:Security:login }

demontpx_user_security_check:
    path:     /login_check
    defaults: { _controller: FOSUserBundle:Security:check }

demontpx_user_security_logout:
    path:     /logout
    defaults: { _controller: FOSUserBundle:Security:logout }
