services:
  demontpx_user.command.create_user:
    class: Demontpx\UserBundle\Command\CreateUserCommand
    arguments:
      - "@demontpx_user.user_manager"
    tags:
      - { name: console.command }

  demontpx_user.command.list_users:
    class: Demontpx\UserBundle\Command\ListUsersCommand
    arguments:
      - "@demontpx_user.user_manager"
    tags:
      - { name: console.command }

  demontpx_user.command.promote_user:
    class: Demontpx\UserBundle\Command\PromoteUserCommand
    arguments:
      - "@demontpx_user.user_manager"
    tags:
      - { name: console.command }

  demontpx_user.command.demote_user:
    class: Demontpx\UserBundle\Command\DemoteUserCommand
    arguments:
      - "@demontpx_user.user_manager"
    tags:
      - { name: console.command }

  demontpx_user.command.enable_user:
    class: Demontpx\UserBundle\Command\EnableUserCommand
    arguments:
      - "@demontpx_user.user_manager"
    tags:
      - { name: console.command }

  demontpx_user.command.disable_user:
    class: Demontpx\UserBundle\Command\DisableUserCommand
    arguments:
      - "@demontpx_user.user_manager"
    tags:
      - { name: console.command }

  demontpx_user.command.change_password:
    class: Demontpx\UserBundle\Command\ChangePasswordCommand
    arguments:
      - "@demontpx_user.user_manager"
    tags:
      - { name: console.command }

  demontpx_user.command.delete_user:
    class: Demontpx\UserBundle\Command\DeleteUserCommand
    arguments:
      - "@demontpx_user.user_manager"
    tags:
      - { name: console.command }
