demontpx_user_manage:
    prefix:   /user/manage/
    resource: "@DemontpxUserBundle/Resources/config/routing/manage.yml"

demontpx_user_security:
    resource: "@DemontpxUserBundle/Resources/config/routing/security.yml"
