parameters:
  demontpx_user.roles:
    ROLE_USER: User
  demontpx_user.fixtures: []

services:
  demontpx_user.form.type.user:
    class: Demontpx\UserBundle\Form\UserType
    arguments:
      - %demontpx_user.roles%
    tags:
      - { name: form.type, alias: 'user' }

  demontpx_user.form.type.user_delete:
    class: Demontpx\UserBundle\Form\UserDeleteType
    tags:
      - { name: form.type, alias: 'user_delete' }
