parameters:
  demontpx_user.roles:
    ROLE_USER: User
  demontpx_user.fixtures: []

  demontpx_user.gravatar.default_size: 80
  demontpx_user.gravatar.default_rating: g
  demontpx_user.gravatar.default_default: mm
  demontpx_user.gravatar.default_force_default: false

services:
  Demontpx\UserBundle\Service\UserManagerInterface: "@demontpx_user.user_manager"
  Demontpx\UserBundle\Service\Gravatar: "@demontpx_user.gravatar"

  demontpx_user.user_manager:
    class: Demontpx\UserBundle\Service\UserManager
    arguments:
      - "@demontpx_user.object_manager"
      - "@demontpx_user.repository.user"
      - "@demontpx_user.password_updater"
    public: true

  demontpx_user.repository.user:
    class: Demontpx\UserBundle\Repository\UserRepository
    factory: ["@demontpx_user.object_manager", getRepository]
    arguments: ["DemontpxUserBundle:User"]

  demontpx_user.object_manager:
    class: Doctrine\Common\Persistence\ObjectManager

  demontpx_user.user_provider:
    class: Demontpx\UserBundle\Service\UserProvider
    arguments:
      - "@demontpx_user.user_manager"

  demontpx_user.password_updater:
    class: Demontpx\UserBundle\Service\PasswordUpdater
    arguments:
      - "@security.encoder_factory"

  demontpx_user.param_converter.user:
    class: Demontpx\UserBundle\ParamConverter\UserParamConverter
    arguments:
      - "@demontpx_user.user_provider"
    tags:
      - { name: request.param_converter, priority: 50 }

  demontpx_user.form.type.user:
    class: Demontpx\UserBundle\Form\UserType
    arguments:
      - "%demontpx_user.roles%"
    tags:
      - { name: form.type }

  demontpx_user.gravatar:
    class: Demontpx\UserBundle\Service\Gravatar
    arguments:
      - "%demontpx_user.gravatar.default_size%"
      - "%demontpx_user.gravatar.default_rating%"
      - "%demontpx_user.gravatar.default_default%"
      - "%demontpx_user.gravatar.default_force_default%"
    public: true

  demontpx_user.twig.gravatar:
    class: Demontpx\UserBundle\Twig\GravatarExtension
    arguments:
      - "@demontpx_user.gravatar"
    tags:
      - { name: twig.extension }

  demontpx_user.data_fixtures.user:
    class: Demontpx\UserBundle\DataFixtures\UserFixtures
    arguments:
      - "%demontpx_user.fixtures%"
    tags:
      - { name: doctrine.fixture.orm }
