parameters:
    demontpx_user.roles:
        ROLE_USER: User
    demontpx_user.fixtures: []

    demontpx_user.gravatar.default_size: 80
    demontpx_user.gravatar.default_rating: g
    demontpx_user.gravatar.default_default: mm
    demontpx_user.gravatar.default_force_default: false

services:
    demontpx_user.user_manager: '@Demontpx\UserBundle\Service\UserManagerInterface'
    demontpx_user.user_provider: '@Demontpx\UserBundle\Service\UserProvider'
    demontpx_user.repository.user: '@Demontpx\UserBundle\Repository\UserRepository'
    demontpx_user.gravatar: '@Demontpx\UserBundle\Service\Gravatar'

    Demontpx\UserBundle\Service\UserManagerInterface: '@Demontpx\UserBundle\Service\UserManager'

    Demontpx\UserBundle\Service\UserManager:
        arguments:
            - '@demontpx_user.entity_manager'
            - '@Demontpx\UserBundle\Repository\UserRepository'
            - '@Demontpx\UserBundle\Service\PasswordUpdater'
            - '@Symfony\Contracts\EventDispatcher\EventDispatcherInterface'
        public: true

    Demontpx\UserBundle\Repository\UserRepository:
        factory: ['@demontpx_user.entity_manager', getRepository]
        arguments: ['DemontpxUserBundle:User']
        public: true

    Demontpx\UserBundle\Service\UserProvider:
        arguments:
            - '@Demontpx\UserBundle\Service\UserManagerInterface'

    Demontpx\UserBundle\Service\PasswordUpdater:
        arguments:
            - '@Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface'

    Demontpx\UserBundle\Service\UserChecker:

    Demontpx\UserBundle\ParamConverter\UserParamConverter:
        arguments:
            - '@Demontpx\UserBundle\Service\UserProvider'
        tags:
            - { name: request.param_converter, priority: 50 }

    Demontpx\UserBundle\Form\UserType:
        arguments:
            - '%demontpx_user.roles%'
        tags: [form.type]

    Demontpx\UserBundle\Service\Gravatar:
        arguments:
            - '%demontpx_user.gravatar.default_size%'
            - '%demontpx_user.gravatar.default_rating%'
            - '%demontpx_user.gravatar.default_default%'
            - '%demontpx_user.gravatar.default_force_default%'
        public: true

    Demontpx\UserBundle\Twig\GravatarExtension:
        arguments:
            - '@Demontpx\UserBundle\Service\Gravatar'
        tags: [twig.extension]

    Demontpx\UserBundle\DataFixtures\UserFixtures:
        arguments:
            - '@Demontpx\UserBundle\Service\UserManagerInterface'
            - '%demontpx_user.fixtures%'
        tags: [doctrine.fixture.orm]

    Demontpx\UserBundle\Command\:
        resource: '../../Command'
        autowire: true
        tags: [console.command]

    Demontpx\UserBundle\Controller\:
        resource: '../../Controller'
        autowire: true
        tags: [controller.service_arguments]
