parameters:
  demontpx_user.roles:
    ROLE_USER: User
  demontpx_user.fixtures: []

  demontpx_user.gravatar.default_size: 80
  demontpx_user.gravatar.default_rating: g
  demontpx_user.gravatar.default_default: mm
  demontpx_user.gravatar.default_force_default: false

services:
  demontpx_user.form.type.user:
    class: Demontpx\UserBundle\Form\UserType
    arguments:
      - "%demontpx_user.roles%"
    tags:
      - { name: form.type }

  demontpx_user.gravatar:
    class: Demontpx\UserBundle\Service\Gravatar
    arguments:
      - "%demontpx_user.gravatar.default_size%"
      - "%demontpx_user.gravatar.default_rating%"
      - "%demontpx_user.gravatar.default_default%"
      - "%demontpx_user.gravatar.default_force_default%"

  demontpx_user.twig.gravatar:
    class: Demontpx\UserBundle\Twig\GravatarExtension
    arguments:
      - "@demontpx_user.gravatar"
    tags:
      - { name: twig.extension }
